In [144]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split,cross_val_score, cross_val_predict
from sklearn import metrics

In [145]:
df = pd.read_csv('abalone.csv')

df['Male'] = df['Sex']
df['Female'] = df['Sex']

df.drop(["Sex"],axis=1, inplace=True)

df['Male'] = df['Male'].map({'M' : 1, 'F' : 0, 'I' : 0})
df['Female'] = df['Female'].map({'M' : 0, 'F' : 1, 'I' : 0})


In [146]:
y = df.iloc[:, 7]

df.drop(["Rings"],axis=1, inplace=True)

x = df.iloc[:,:]

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x = scaler.fit_transform(x)

# 1. For Test set = 33.33%

In [147]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.3333)

## i) Naive Bayes

In [148]:
gaussian_nb = GaussianNB()
y_prediction = gaussian_nb.fit(x_train, y_train).predict(x_test)
print("Accuracy is :", metrics.accuracy_score(y_test, y_prediction)*100, "%")

Accuracy is : 23.618090452261306 %


## ii) K-NN

In [149]:
k_nn = KNeighborsClassifier()
y_prediction_knn= k_nn.fit(x_train,y_train).predict(x_test)
print("Accuracy is : ", metrics.accuracy_score(y_test,y_prediction_knn)*100, "%")

Accuracy is :  23.043790380473798 %


## iii) Decision Tree

In [150]:
DT_classifier= DecisionTreeClassifier(random_state=1)
y_prediction_DT_classifier= DT_classifier.fit(x_train, y_train).predict(x_test)
print("Accuracy is :", metrics.accuracy_score(y_test, y_prediction_DT_classifier)*100, "%")

Accuracy is : 20.96195262024408 %


# 2. Random Subsampling

In [151]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.25, random_state = 1)

## i) Naive Bayes

In [152]:
gaussian_nb = GaussianNB()
y_prediction1 = gaussian_nb.fit(x_train, y_train).predict(x_test)
print("Accuracy is :", metrics.accuracy_score(y_test, y_prediction1)*100, "%")

Accuracy is : 22.392344497607656 %


## ii) K-NN

In [153]:
y_prediction_knn1= k_nn.fit(x_train,y_train).predict(x_test)
print("Accuracy is :", metrics.accuracy_score(y_test,y_prediction_knn1)*100, "%")

Accuracy is : 24.210526315789473 %


## iii) Decision Tree

In [154]:
DT_classifier1= DecisionTreeClassifier(random_state=1)
DT_classifier1= DT_classifier1.fit(x_train, y_train)
y_prediction1= DT_classifier1.predict(x_test)
print("Accuracy is :", metrics.accuracy_score(y_test, y_prediction1)*100, "%")

Accuracy is : 19.330143540669855 %


# 3. Cross Validation

## i) Naive Bayes

In [155]:
gaussian_nb = GaussianNB()
y_prediction2 = cross_val_predict(gaussian_nb, x, y ,cv=3)
print("Accuracy is :", metrics.accuracy_score(y, y_prediction2)*100, "%")

Accuracy is : 22.384486473545607 %


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  % (min_groups, self.n_splits)), UserWarning)


In [156]:
y_score2 = cross_val_score(gaussian_nb, x, y ,cv=3)
print("Accuracy is:", np.mean(y_score2)*100, "%")
print(y_score2)

Accuracy is: 22.38527407150696 %
[0.19095477 0.24281609 0.23778736]


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  % (min_groups, self.n_splits)), UserWarning)


## ii) K-NN

In [157]:
y_prediction_knn2= cross_val_predict(k_nn, x, y, cv=4)
print("Accuracy is :", metrics.accuracy_score(y,y_prediction_knn2)*100, "%")

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=4.
  % (min_groups, self.n_splits)), UserWarning)


Accuracy is : 22.64783337323438 %


In [158]:
y_score2 = cross_val_score(k_nn, X, y, cv=4)
print("Accuracy is :", np.mean(y_score2)*100, "%")
print(y_score2)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=4.
  % (min_groups, self.n_splits)), UserWarning)


Accuracy is : 22.64851326330455 %
[0.19808612 0.24233716 0.21360153 0.25191571]


## iii) Decision Tree

In [159]:
DT_classifier2= DecisionTreeClassifier(random_state=1)
y_prediction2= cross_val_predict(DT_classifier2, x, y ,cv=4)

print("Accuracy is :", metrics.accuracy_score(y, y_pred2)*100, "%")

Accuracy is : 19.607373713191286 %


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=4.
  % (min_groups, self.n_splits)), UserWarning)


In [160]:
y_score2 = cross_val_score(DT_classifier2, x, y ,cv=4)
print("Accuracy is :", np.mean(y_score2)*100, "%")
print(y_score2)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=4.
  % (min_groups, self.n_splits)), UserWarning)


Accuracy is : 19.607921318447634 %
[0.17320574 0.20689655 0.20785441 0.19636015]
